---
title: 'Introduction'
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- What software development methods best adapt to developing XR systems?
- What XR user design considerations need to be accounted for
different modalities of interaction and sensing in XR systems?
- How is interactivity in an XR system implemented at a high-level in code? 

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Learn basic elements of XR-system development including software development cycle, 
design consideration.
- Understand the processes to elucidate and design an XR-system
focused on a user.
- Learn about basics of game engine or systems which are used
to build interactive graphic applications.

::::::::::::::::::::::::::::::::::::::::::::::::


## Interactive Experiences

> Knowledge is acquired in a continuous process of accommodating prior expectations and beliefs to new realities learned through interactive experiences (Jensen, 1999)

Jensen, N. (1999). Children, teenagers and adults in museums: a developmental perspective. In Hooper-Greenhill, E. (Ed.), The Educational Role of the Museum, 2nd ed., Routledge.


Interactive experiences are the basis of knowledge (constructivist theory of knowing).

Experiences cannot just be provided or delivered.

In **User Design (UX)**, interactive experiences connect users with an ‘environment’ in non-passive ways.

An **experience curator** designs an experiential framework, but the way the experience is perceived belongs to the user.



::::::::::::::::::::::::::::::::::::: keypoints 

- Lesson covers basic of design and software development cycles

::::::::::::::::::::::::::::::::::::::::::::::::

